project:
  type: website
  output-dir: _site

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: machine learning.qmd
        text: Machine Learning
      - href: Linear Regression.qmd
        text: Linear Regression

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



