project:
  type: website
  output-dir: _site

website:
  title: "project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: machine learning.qmd
        text: Machine Learning

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



